In [2]:
pip install tf-keras

Collecting tf-keras
  Downloading tf_keras-2.21.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow<2.22,>=2.21 (from tf-keras)
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow<2.22,>=2.21->tf-keras)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.32.3)
Requirement already satisfied: setuptools in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (1.71.0)
Collecting keras>=3.12.0 (from tensorflow<2.22,>=2.21->tf-keras)
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (2.2.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow<2.22,>=2.21->tf-keras) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.22,>=2.21->tf-keras) (2025.4.26)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from astunparse>=1.6.0->tensorflow<2.22,>=2.21->tf-keras) (0.45.1)
Requirement already satisfied: rich in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (13.9.4)
Requirement already satisfied: namex in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.0.8)
Requirement already satisfied: optree in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow<2.22,>=2.21->tf-keras) (0.1.2)
Downloading tf_keras-2.21.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 19.0 MB/s  0:00:00
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
    --------------------------------------- 4.7/351.2 MB 25.0 MB/s eta 0:00:14
   - -------------------------------------- 11.0/351.2 MB 26.8 MB/s eta 0:00:13
   -- ------------------------------------- 18.1/351.2 MB 29.5 MB/s eta 0:00:12
   -- ------------------------------------- 26.2/351.2 MB 31.5 MB/s eta 0:00:11
   --- ------------------------------------ 34.1/351.2 MB 32.7 MB/s eta 0:00:10
   ---- ----------------------------------- 41.2/351.2 MB 32.6 MB/s eta 0:00:10
   ----- ---------------------------------- 45.6/351.2 MB 31.2 MB/s eta 0:00:10
   ----- ---------------------------------- 48.5/351.2 MB 29.0 MB/s eta 0:00:11
   ----- ---------------------------------- 51.6/351.2 MB 27.2 MB/s eta 0:00:12
   ------ --------------------------------- 55.1/351.2 MB 26.1 MB/s eta 0:00:12
   ------ --------------------------------- 59.5/351.2 MB 25.5 MB/s eta 0:00:12
   ------- -------------------------------- 64.0/351.2 MB 25.2 MB/s eta 0:00:12
   ------- -------------------------------- 68.2/351.2 MB 24.8 MB/s eta 0:00:12
   -------- ------------------------------- 73.1/351.2 MB 24.7 MB/s eta 0:00:12
   -------- ------------------------------- 76.5/351.2 MB 24.2 MB/s eta 0:00:12
   --------- ------------------------------ 80.5/351.2 MB 23.8 MB/s eta 0:00:12
   --------- ------------------------------ 84.9/351.2 MB 23.6 MB/s eta 0:00:12
   ---------- ----------------------------- 88.1/351.2 MB 23.3 MB/s eta 0:00:12
   ---------- ----------------------------- 91.2/351.2 MB 22.8 MB/s eta 0:00:12
   ---------- ----------------------------- 94.4/351.2 MB 22.4 MB/s eta 0:00:12
   ----------- ---------------------------- 97.3/351.2 MB 22.1 MB/s eta 0:00:12
   ----------- --------------------------- 101.4/351.2 MB 22.0 MB/s eta 0:00:12
   ----------- --------------------------- 105.9/351.2 MB 22.0 MB/s eta 0:00:12
   ------------ -------------------------- 109.8/351.2 MB 21.8 MB/s eta 0:00:12
   ------------ -------------------------- 114.8/351.2 MB 21.9 MB/s eta 0:00:11
   ------------- ------------------------- 119.0/351.2 MB 21.8 MB/s eta 0:00:11
   ------------- ------------------------- 123.2/351.2 MB 21.8 MB/s eta 0:00:11
   -------------- ------------------------ 127.1/351.2 MB 21.7 MB/s eta 0:00:11
   -------------- ------------------------ 130.5/351.2 MB 21.5 MB/s eta 0:00:11
   -------------- ------------------------ 134.7/351.2 MB 21.4 MB/s eta 0:00:11
   --------------- ----------------------- 138.4/351.2 MB 21.4 MB/s eta 0:00:10
   --------------- ----------------------- 142.3/351.2 MB 21.3 MB/s eta 0:00:10
   ---------------- ---------------------- 145.8/351.2 MB 21.1 MB/s eta 0:00:10
   ---------------- ---------------------- 149.9/351.2 MB 21.1 MB/s eta 0:00:10
   ----------------- --------------------- 153.9/351.2 MB 21.0 MB/s eta 0:00:10
   ----------------- --------------------- 157.8/351.2 MB 21.0 MB/s eta 0:00:10
   ----------------- --------------------- 161.5/351.2 MB 20.8 MB/s eta 0:00:10
   ------------------ -------------------- 164.4/351.2 MB 20.6 MB/s eta 0:00:10
   ------------------ -------------------- 167.8/351.2 MB 20.5 MB/s eta 0:00:09
   ------------------- ------------------- 171.7/351.2 MB 20.5 MB/s eta 0:00:09
   ------------------- ------------------- 176.4/351.2 MB 20.6 MB/s eta 0:00:09
   -------------------- ------------------ 181.1/351.2 MB 20.6 MB/s eta 0:00:09
   -------------------- ------------------ 185.1/351.2 MB 20.6 MB/s eta 0:00:09
   -------------------- ------------------ 188.7/351.2 MB 20.5 MB/s eta 0:00:08
   --------------------- ----------------- 192.7/351.2 MB 20.5 MB/s eta 0:00:08
   --------------------- ----------------- 196.3/351.2 MB 20.4 MB/s eta 0:00:08
   ---------------------- ---------------- 200.3/351.2 MB 20.4 MB/s eta 0:00:08
   ---------------------- ---------------- 204.5/351.2 MB 20.4 MB/s eta 0:00:08
   ----------------------- --------------- 207.6/351.2 MB 20.3 MB/s eta 0:00:08
   ----------------------- --------------- 212.1/351.2 MB 20.3 MB/s eta 0:00:07
   ----------------------- --------------- 216.0/351.2 MB 20.3 MB/s eta 0:00:07
   ------------------------ -------------- 219.7/351.2 MB 20.2 MB/s eta 0:00:07
   ------------------------ -------------- 222.8/351.2 MB 20.1 MB/s eta 0:00:07
   ------------------------- ------------- 227.3/351.2 MB 20.1 MB/s eta 0:00:07
   ------------------------- ------------- 231.7/351.2 MB 20.1 MB/s eta 0:00:06
   -------------------------- ------------ 235.7/351.2 MB 20.1 MB/s eta 0:00:06
   -------------------------- ------------ 239.6/351.2 MB 20.1 MB/s eta 0:00:06
   --------------------------- ----------- 243.8/351.2 MB 20.1 MB/s eta 0:00:06
   --------------------------- ----------- 246.7/351.2 MB 20.0 MB/s eta 0:00:06
   --------------------------- ----------- 250.3/351.2 MB 19.9 MB/s eta 0:00:06
   ---------------------------- ---------- 254.3/351.2 MB 19.9 MB/s eta 0:00:05
   ---------------------------- ---------- 257.9/351.2 MB 19.8 MB/s eta 0:00:05
   ----------------------------- --------- 261.4/351.2 MB 19.8 MB/s eta 0:00:05
   ----------------------------- --------- 266.3/351.2 MB 19.8 MB/s eta 0:00:05
   ------------------------------ -------- 271.3/351.2 MB 19.8 MB/s eta 0:00:05
   ------------------------------ -------- 275.3/351.2 MB 19.6 MB/s eta 0:00:04
   ------------------------------- ------- 279.2/351.2 MB 19.5 MB/s eta 0:00:04
   ------------------------------- ------- 282.6/351.2 MB 19.3 MB/s eta 0:00:04
   ------------------------------- ------- 285.7/351.2 MB 19.1 MB/s eta 0:00:04
   -------------------------------- ------ 289.1/351.2 MB 18.9 MB/s eta 0:00:04
   -------------------------------- ------ 292.0/351.2 MB 18.8 MB/s eta 0:00:04
   -------------------------------- ------ 296.7/351.2 MB 18.6 MB/s eta 0:00:03
   --------------------------------- ----- 301.7/351.2 MB 18.6 MB/s eta 0:00:03
   ---------------------------------- ---- 306.2/351.2 MB 18.5 MB/s eta 0:00:03
   ---------------------------------- ---- 310.1/351.2 MB 18.6 MB/s eta 0:00:03
   ---------------------------------- ---- 314.0/351.2 MB 18.7 MB/s eta 0:00:02
   ----------------------------------- --- 318.0/351.2 MB 18.7 MB/s eta 0:00:02
   ----------------------------------- --- 321.1/351.2 MB 18.7 MB/s eta 0:00:02
   ------------------------------------ -- 325.1/351.2 MB 18.6 MB/s eta 0:00:02
   ------------------------------------ -- 329.0/351.2 MB 18.6 MB/s eta 0:00:02
   ------------------------------------ -- 332.7/351.2 MB 18.5 MB/s eta 0:00:02
   ------------------------------------- - 336.9/351.2 MB 18.5 MB/s eta 0:00:01
   ------------------------------------- - 340.8/351.2 MB 18.5 MB/s eta 0:00:01
   --------------------------------------  343.9/351.2 MB 18.5 MB/s eta 0:00:01
   --------------------------------------  346.8/351.2 MB 18.4 MB/s eta 0:00:01
   --------------------------------------  350.7/351.2 MB 18.5 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 18.5 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 18.5 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 18.5 MB/s eta 0:00:01
   ---------------------------------------- 351.2/351.2 MB 17.7 MB/s  0:00:18
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading keras-3.13.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 16.1 MB/s  0:00:00
Installing collected packages: protobuf, keras, tensorflow, tf-keras

  Attempting uninstall: protobuf

    Found existing installation: protobuf 5.29.5

    Uninstalling protobuf-5.29.5:

      Successfully uninstalled protobuf-5.29.5

   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
   ---------------------------------------- 0/4 [protobuf]
  Attempting uninstall: keras
   ---------------------------------------- 0/4 [protobuf]
    Found existing installation: keras 3.11.3
   ---------------------------------------- 0/4 [protobuf]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
    Uninstalling keras-3.11.3:
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
      Successfully uninstalled keras-3.11.3
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
   ---------- ----------------------------- 1/4 [keras]
  Attempting uninstall: tensorflow
   ---------- ----------------------------- 1/4 [keras]
    Found existing installation: tensorflow 2.20.0
   ---------- ----------------------------- 1/4 [keras]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
    Uninstalling tensorflow-2.20.0:
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
      Successfully uninstalled tensorflow-2.20.0
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]
   -------------------- ------------------- 2/4 [tensorflow]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\~upb'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages\~ensorflow'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googleapis-common-protos 1.70.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
google-api-core 2.24.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5, but you have protobuf 7.34.1 which is incompatible.
grpcio-status 1.71.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.1 which is incompatible.
proto-plus 1.26.1 requires protobuf<7.0.0,>=3.19.0, but you have protobuf 7.34.1 which is incompatible.
streamlit 1.50.0 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.

In [3]:
pip install transformers

Requirement already satisfied: transformers in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.52.4)
Requirement already satisfied: filelock in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.33.0)
Requirement already satisfied: numpy>=1.17 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->transformers) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

WARNING:tensorflow:From c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
train_data = pd.read_csv("samsum-train.csv")
val_data = pd.read_csv("samsum-validation.csv")

In [3]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [4]:
train_data["dialogue"][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [5]:
train_data.shape

(14732, 3)

In [6]:
val_data.shape

(818, 3)

In [8]:
# random sampling
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

In [9]:
train_data.shape

(4000, 3)

# Data pre-processing

In [10]:
import re

def clean_data(text):
    text = re.sub(r"\r\n", " ", text) # lines
    text = re.sub(r"\s+", " ", text) # spaces
    text = re.sub(r"<.*?>", " ", text) # html tags <p> <h1>
    text = text.strip().lower()
    return text

In [11]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

# Tokenize

In [12]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")

tokenizer_config.json: 0.00B [00:00, ?B/s]

c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\surya\.cache\huggingface\hub\models--t5-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [13]:
# raw data => tokenized inputs for fine-tuning

def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length=512, truncation=True)
    targets = tokenizer(data["summary"], padding="max_length", max_length=150, truncation=True)

    inputs["labels"] = targets["input_ids"] # token ids => add to input as labels
    return inputs

In [ ]:
train_dataset = train_data.apply(tokenize, axis=1).tolist()
val_dataset = val_data.apply(tokenize, axis=1).tolist()

In [15]:
train_dataset[0]

{'input_ids': [836, 6961, 10, 3, 13133, 1240, 226, 6, 103, 25, 341, 3884, 22269, 58, 1240, 226, 10, 7102, 3158, 307, 97, 150, 1616, 3, 10, 61, 17945, 6, 3, 23, 103, 6, 125, 31, 7, 95, 58, 836, 6961, 10, 320, 6, 82, 7930, 19, 479, 21, 841, 113, 228, 3884, 376, 6, 78, 3, 23, 816, 81, 25, 5, 1240, 226, 10, 417, 589, 55, 125, 593, 19, 3, 88, 44, 230, 58, 836, 6961, 10, 3, 107, 51, 233, 614, 12, 817, 6, 43, 29, 31, 17, 1380, 3, 117, 61, 3, 23, 317, 3, 88, 131, 2746, 12, 36, 6720, 295, 6, 78, 3, 88, 1077, 523, 128, 12, 43, 9029, 28, 5, 1240, 226, 10, 150, 682, 6, 8, 589, 19, 3, 23, 163, 43, 1911, 1135, 7, 11, 62, 26, 1496, 1135, 7, 326, 233, 836, 6961, 10, 3, 32, 107, 82, 6, 24, 31, 7, 626, 55, 3, 88, 31, 7, 882, 3, 9, 3164, 4024, 6, 68, 3, 88, 243, 62, 26, 1496, 1135, 2993, 1399, 5, 1240, 226, 10, 248, 258, 55, 2049, 21, 48, 55, 3, 10, 61, 836, 6961, 10, 4244, 1024, 1024, 6, 150, 682, 55, 78, 6, 54, 3, 23, 1499, 376, 39, 381, 58, 1240, 226, 10, 13, 503, 3, 10, 61, 836, 6961, 10, 3, 88, 31, 195, 580, 25, 16, 8, 2272, 6, 62, 31, 60, 341, 16, 8, 828, 5, 3, 88, 31, 7, 882, 5256, 18, 23185, 78, 3, 88, 54, 92, 1499, 25, 30, 125, 31, 7, 1120, 3, 10, 26, 1240, 226, 10, 4244, 1024, 1024, 6, 248, 55, 149, 33, 25, 57, 8, 194, 58, 3, 23, 3, 2381, 15, 25, 3, 9, 1975, 21, 48, 55, 836, 6961, 10, 6979, 95, 6, 25, 3, 2381, 15, 140, 1327, 6, 68, 3, 23, 133, 16725, 281, 91, 6, 62, 43, 78, 231, 3, 11907, 95, 1240, 226, 10, 17945, 6, 902, 24, 613, 13, 39, 7, 55, 2993, 882, 1633, 6, 3, 28848, 10769, 836, 6961, 10, 54, 31, 17, 15524, 3, 117, 61, 19, 3, 7, 6010, 1135, 66, 269, 58, 1240, 226, 10, 417, 589, 6, 752, 140, 253, 3, 9, 286, 11, 56, 752, 25, 214, 38, 9, 102, 3, 10, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [836, 6961, 987, 7, 1240, 226, 3, 99, 3, 88, 228, 3884, 112, 7930, 22269, 5, 1240, 226, 2065, 7, 5, 836, 6961, 11, 1240, 226, 56, 942, 30, 3, 7, 6010, 1135, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [ ]:
# input ids - dialogue => token ids

# 1 => EOS, 0 => padding

# attention mask
# labels - target => summary token

In [16]:
len(train_dataset[0]["input_ids"])

512

In [17]:
type(train_dataset)
type(val_dataset)

list

# Working with our Model

In [18]:
# NLP => generation task

model = T5ForConditionalGeneration.from_pretrained("t5-small")

config.json: 0.00B [00:00, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [20]:
import torch

if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("device: ", device)
model.to(device)

device:  cpu

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [21]:
# Training Arguments

training_args = TrainingArguments(
    output_dir = "./results",

    num_train_epochs=6,
    weight_decay=0.01,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    eval_strategy="epoch",
    save_strategy="epoch",

    warmup_steps=500
    # 0 => lr default
)

In [22]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

In [23]:
# train the model
trainer.train()

c:\Users\surya\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

KeyboardInterrupt:

In [ ]:
# model load => fine-tune => save the model

In [ ]:
model.save_pretrained("./saved_summary_model")
tokenizer.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./saved_summary_model/tokenizer_config.json',
 './saved_summary_model/tokenizer.json')

In [ ]:
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

## Test the core logic for summarization

In [ ]:
def summarize_dialogue(dialogue):
    dialogue = clean_data(dialogue) # clean

    # tokenize
    inputs = tokenizer(
        dialogue,
        padding="max_length",
        max_length=512,
        truncation=True,
        return_tensors="pt"
    ).to(device)

    # generate the summary => token ids
    model.to(device)
    targets = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=150,
        num_beams=4,
        early_stopping=True
    )
    
    # decoded our output
    summary = tokenizer.decode(targets[0], skip_special_tokens=True) # EOS, SEP
    return summary

In [ ]:
test_dialogue = """ 
Reporter: In today's technology news, artificial intelligence continues to expand rapidly across industries, from healthcare to finance and education. Recent reports suggest that AI adoption has significantly increased over the past few years.

Reporter: Companies are investing heavily in machine learning systems to automate tasks, improve decision-making, and enhance customer experiences. However, this growth has also raised questions about job displacement and ethical concerns.

Expert: AI systems are becoming more capable due to advances in deep learning and access to large datasets. These models can now perform complex tasks such as language understanding, image recognition, and even code generation.

Expert: At the same time, there are valid concerns about bias in AI models, as they often reflect the data they are trained on. Ensuring fairness and transparency is becoming a key area of research.

Reporter: Governments and organizations are beginning to introduce regulations to guide the development and deployment of AI technologies. The goal is to balance innovation with accountability.

Expert: Another challenge is explainability. Many modern AI systems, especially deep neural networks, operate as “black boxes,” making it difficult to understand how decisions are made.

Reporter: Experts also highlight the importance of responsible AI development, including data privacy, security, and long-term societal impact.

Expert: Looking ahead, collaboration between researchers, policymakers, and industry leaders will be crucial to ensure that AI systems are developed and used in a safe and beneficial way.
"""

summary = summarize_dialogue(test_dialogue)

print("Summary: ", summary)

Summary:  ai systems are becoming more capable due to advances in deep learning and access to large datasets. experts highlight the importance of responsible ai development, including data privacy, security, and long-term societal impact.